#! /bin/sh
case "$1" in
    start)
        echo "Starting ldd modules"
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping ldd modules"
        scull_unload
        module_unload faulty
        rmmod hello
        ;;
    status)
        echo "Status of ldd modules"
        echo $?
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
